# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MacrosUIMk1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 600)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(380, 20, 256, 521))
        self.listWidget.setObjectName("listWidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 30, 301, 511))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bHotKey = QtWidgets.QPushButton(self.widget)
        self.bHotKey.setObjectName("bHotKey")
        self.verticalLayout.addWidget(self.bHotKey)
        self.bPress = QtWidgets.QPushButton(self.widget)
        self.bPress.setObjectName("bPress")
        self.verticalLayout.addWidget(self.bPress)
        self.bMultiPress = QtWidgets.QPushButton(self.widget)
        self.bMultiPress.setObjectName("bMultiPress")
        self.verticalLayout.addWidget(self.bMultiPress)
        self.bHold = QtWidgets.QPushButton(self.widget)
        self.bHold.setObjectName("bHold")
        self.verticalLayout.addWidget(self.bHold)
        self.bRelease = QtWidgets.QPushButton(self.widget)
        self.bRelease.setObjectName("bRelease")
        self.verticalLayout.addWidget(self.bRelease)
        self.bWait = QtWidgets.QPushButton(self.widget)
        self.bWait.setObjectName("bWait")
        self.verticalLayout.addWidget(self.bWait)
        self.bWrite = QtWidgets.QPushButton(self.widget)
        self.bWrite.setObjectName("bWrite")
        self.verticalLayout.addWidget(self.bWrite)
        self.bCopy = QtWidgets.QPushButton(self.widget)
        self.bCopy.setObjectName("bCopy")
        self.verticalLayout.addWidget(self.bCopy)
        self.bMoveUp = QtWidgets.QPushButton(self.widget)
        self.bMoveUp.setObjectName("bMoveUp")
        self.verticalLayout.addWidget(self.bMoveUp)
        self.bMoveDown = QtWidgets.QPushButton(self.widget)
        self.bMoveDown.setObjectName("bMoveDown")
        self.verticalLayout.addWidget(self.bMoveDown)
        self.bRemove = QtWidgets.QPushButton(self.widget)
        self.bRemove.setObjectName("bRemove")
        self.verticalLayout.addWidget(self.bRemove)
        self.bTrigger = QtWidgets.QPushButton(self.widget)
        self.bTrigger.setObjectName("bTrigger")
        self.verticalLayout.addWidget(self.bTrigger)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 662, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vic\'s Mcaros"))
        self.bHotKey.setText(_translate("MainWindow", "Hotkey"))
        self.bPress.setText(_translate("MainWindow", "Press"))
        self.bMultiPress.setText(_translate("MainWindow", "Multi Press"))
        self.bHold.setText(_translate("MainWindow", "Hold"))
        self.bRelease.setText(_translate("MainWindow", "Release"))
        self.bWait.setText(_translate("MainWindow", "Wait"))
        self.bWrite.setText(_translate("MainWindow", "Write"))
        self.bCopy.setText(_translate("MainWindow", "Copy"))
        self.bMoveUp.setText(_translate("MainWindow", "Move Up"))
        self.bMoveDown.setText(_translate("MainWindow", "Move Down"))
        self.bRemove.setText(_translate("MainWindow", "Remove"))
        self.bTrigger.setText(_translate("MainWindow", "Start"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
